language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

before_install: pip install pytest pytest-cov coveralls

install: python setup.py install

script:
  - py.test -v -s test_redirectory.py --doctest-modules redirectory.py
  # One doctest fails when measuring coverage so turn off doctests
  - py.test -v -s --cov redirectory test_redirectory.py

after_success: coveralls
